### ISSUE TITLE
Software clone detected in GenericStatisticsViewHolder.java

### ISSUE THREAD

**Issue by nishith-soni** [rilling/opentracksFall2024#26]
Describe the clone
These two code snippets are essentially clones of each other with one key distinction: the description text that is set in statsDescriptionMain. This difference reflects the different contexts in which these two classes are used. While both classes use the same logic to format and display the speed/pace, they appear to be intended for slightly different display purposes based on the context provided by the string resources.

![cmd issue](https://github.com/user-attachments/assets/4cc1901b-b6f8-4398-8057-fabad70d24a1)

Location of the clones
Starting at line 168 of src\main\java\de\dennisguse\opentracks\viewmodels\GenericStatisticsViewHolder.java
Starting at line 185 of src\main\java\de\dennisguse\opentracks\viewmodels\GenericStatisticsViewHolder.java

Clone Type
Type 2

Expected outcome
To fix this, we can refactor the code by creating a common method or class that handles the common logic for both cases, and then allow the specific description text to be passed dynamically.

Make a function to handle common logic in both classes AverageMovingPace and Average Pace

Code before refactoring

![Screenshot 2024-11-07 100627](https://github.com/user-attachments/assets/fe565c83-94bb-4519-9d5e-4c278db018cc)

Code after refactoring

![solution](https://github.com/user-attachments/assets/b4d2476e-cf1e-4199-9f1c-b79e499200b9)

Function code

![function](https://github.com/user-attachments/assets/dc10e2c7-1a4f-4b46-abe0-6e6781ceaee3)

Additional context
Issue can be fixed by making a function and calling it in both classes.

**Comment by anurag444** [comment]
Issue resolved, closing this
