### ISSUE TITLE
[Refactor] Eliminate duplication in PreferencesUtils.java Group 21

### ISSUE THREAD

**Issue by tejasvi541** [rilling/opentracksFall2024#28]
[Refactor] Eliminate duplication in PreferencesUtils.java

## Issue Description
The `getMaxRecordingDistanceEntries()` and `getThresholdHorizontalAccuracyEntries()` methods in `PreferencesUtils.java` contain a significant amount of duplicated code for generating the entries. This duplication makes the code harder to maintain and increases the risk of bugs. 
![Screenshot 2024-11-04 115353](https://github.com/user-attachments/assets/b5347158-a2f2-456e-9245-13c95a48f316)

Clone Type - 1

The key characteristics of the clone detected in the PreferencesUtils.java file are:
- Exact Copy: The 16-line block of code was exactly the same between the two locations, without any variations.
- Same Length: Both instances of the clone were 16 lines (103 tokens) long.
- Same Functionality: The duplicated code likely performed the same or very similar functionality in both locations.

Location - 
- Starting at line 515 of W:\Concordia\Fall2024\SOEN6431\opentracksFall2024Tejasvi\src\main\java\de\dennisguse\opentracks\settings\PreferencesUtils.java
- Starting at line 587 of W:\Concordia\Fall2024\SOEN6431\opentracksFall2024Tejasvi\src\main\java\de\dennisguse\opentracks\settings\PreferencesUtils.java

## Proposed Solution
Refactor the duplicated code by extracting a common method that can be reused in both places. This will improve the code's maintainability and readability.

**Comment by anurag444** [comment]
Issue resolved, Closing
