### ISSUE TITLE
Software Clone detected in DirectoryChooserActivity.java

### ISSUE THREAD

**Issue by sanju-27** [rilling/opentracksFall2024#30]
### About the issue:
Software clone detected in DirectoryChooserActivity.java
**Size of clone:** 79 tokens (14 lines)
**File location of clone:**  java\de\dennisguse\opentracks\io\file\importer\DirectoryChooserActivity.java

### Clone type:
Type 1. This is a direct clone. The contents were repeated for simplicity.

![image](https://github.com/user-attachments/assets/eb5853c0-8c47-469b-9417-511e54f7eed9)

### Proposed solution:

- Removed unwanted overridden methods and combined parent method
- Added an extra method to create a new export activity and add basic functionalities.

**Comment by anurag444** [comment]
Issue resolved, Closing
