### ISSUE TITLE
Technical Debt - Extract this nested code block into a method.

### ISSUE THREAD

**Issue by sankarsiva007** [rilling/opentracksFall2024#5]
Technical Debt Description : The readability of the initial code was low due to the code blocks inside the onCreate method. Now, we have extracted the code block into a method which makes it more readable and reusable.

Location :
File:  TrackStoppedActivity.java
Path: src/main/java/de/dennisguse/opentracks/TrackStoppedActivity.java 

Reason for Change : As there is so much logic in the onCreate method, it makes difficult for the users to maintain and understand it. By extracting like this, we can improve the speed of execution as the new code is simpler than the older version due to the use of method. This also promoted single responsibility criteria for the method that enhances maintainability and readability

Expected Outcome : With this change, we can improve the Readability of the code as the onCreate method is comparitively easier to use and understand now. We also improved the reusability of the code by increasing the speed of the code and also the maintainability is improved as any future changes required to the logic of speed display can be made without impacting the logic of onCreate process.

Screenshot  : 
![Screenshot 2024-10-09 180152](https://github.com/user-attachments/assets/617b4032-1cfc-4c2f-a3da-3ed084e03d3b)

**Comment by 0matleb2** [comment]
While it makes sense for traceability reasons to create our issues on the prof's repo, the instructions were to create them in our group repos.

**Comment by sankarsiva007** [comment]
Hi @0matleb2 ,
I apologize for the issue.
I was intended to create on our team repo, but it automatically switches to prof's repo. We noticed the same issue repeating multiple times and we had to manually open our group's repo multiple times.

Thanks,
Siva.
